
server:
  port: 8070

---

spring:
  config:
    activate:
      on-profile: development
server:
  port: 8060

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  port: 8050

---

#---
#spring:
#  config:
#    activate:
#      on-profile: prod