
spring:
  config:
    activate:
      on-profile: development
---
spring:
  profiles:
    active: development
---
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
---
spring:
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://production-host:3306/prod_db
    username: prod
    password: production
